title: "LayerZero"
description: "A cybersecurity learning journal by Sahana — decoding threats, code, and curiosity."
url: "https://sahana-n-murthy.github.io"
baseurl: "/LayerZero"  # IMPORTANT: use your repo name here for GitHub Pages

# Theme
theme: minima

# Enable blog post listing
show_excerpts: true
paginate: 5

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown engine
markdown: kramdown

# Permalinks for blog posts
permalink: /:year/:month/:day/:title/

# Exclude these from the output site
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

# Author (optional)
author: "Sahana Narasimha Murthy"
email: "sahanamurthy2010@gmail.com"

